In [1]:
import yfinance as yf
import pandas as pd

In [2]:
spy = yf.Ticker("SPY")

In [3]:
spy.options

('2026-07-24',
 '2026-07-27',
 '2026-07-28',
 '2026-07-29',
 '2026-07-30',
 '2026-07-31',
 '2026-08-03',
 '2026-08-04',
 '2026-08-05',
 '2026-08-06',
 '2026-08-07',
 '2026-08-14',
 '2026-08-21',
 '2026-08-28',
 '2026-08-31',
 '2026-09-04',
 '2026-09-18',
 '2026-09-30',
 '2026-10-16',
 '2026-10-30',
 '2026-11-20',
 '2026-11-30',
 '2026-12-18',
 '2026-12-31',
 '2027-01-15',
 '2027-03-19',
 '2027-03-31',
 '2027-06-17',
 '2027-06-30',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-06-16',
 '2028-12-15')

In [4]:
expiry = spy.options[0]

print(expiry)

2026-07-24

In [5]:
option_chain = spy.option_chain(expiry)

In [6]:
calls = option_chain.calls

puts = option_chain.puts

In [7]:
calls.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,SPY260724C00500000,2026-07-22 18:31:15+00:00,500.0,248.89,0.0,0.0,0.0,0.0,1.0,2003,0.00001,True,REGULAR,USD
1,SPY260724C00505000,2026-07-13 16:56:30+00:00,505.0,245.53,0.0,0.0,0.0,0.0,NaN,1,0.00001,True,REGULAR,USD
2,SPY260724C00510000,2026-07-13 16:56:45+00:00,510.0,240.41,0.0,0.0,0.0,0.0,NaN,1,0.00001,True,REGULAR,USD
3,SPY260724C00515000,2026-07-23 19:44:12+00:00,515.0,221.74,0.0,0.0,0.0,0.0,1.0,1,0.00001,True,REGULAR,USD
4,SPY260724C00520000,2026-07-23 19:45:39+00:00,520.0,216.68,0.0,0.0,0.0,0.0,2.0,2,0.00001,True,REGULAR,USD

In [8]:
puts.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,SPY260724P00500000,2026-07-22 18:31:17+00:00,500.0,0.01,0.0,0.0,0.0,0.0,1,3239,0.500005,False,REGULAR,USD
1,SPY260724P00505000,2026-07-17 19:03:54+00:00,505.0,0.01,0.0,0.0,0.0,0.0,102,1576,0.500005,False,REGULAR,USD
2,SPY260724P00510000,2026-07-17 18:48:21+00:00,510.0,0.02,0.0,0.0,0.0,0.0,20,425,0.500005,False,REGULAR,USD
3,SPY260724P00515000,2026-07-17 18:23:06+00:00,515.0,0.01,0.0,0.0,0.0,0.0,5,986,0.500005,False,REGULAR,USD
4,SPY260724P00520000,2026-07-17 18:22:17+00:00,520.0,0.03,0.0,0.0,0.0,0.0,11,881,0.500005,False,REGULAR,USD

In [9]:
print(calls.columns)

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask',
       'change', 'percentChange', 'volume', 'openInterest',
       'impliedVolatility', 'inTheMoney', 'contractSize', 'currency'],
      dtype='str')

In [10]:
calls.to_csv("../data/options/SPY_Calls.csv", index=False)

puts.to_csv("../data/options/SPY_Puts.csv", index=False)

print("Option chain saved successfully!")

Option chain saved successfully!

In [11]:
len(spy.options)

34