In [1]:
import pandas as pd

calls = pd.read_csv("../data/options/SPY_Calls.csv")

calls.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,SPY260724C00500000,2026-07-22 18:31:15+00:00,500.0,248.89,236.39,238.19,0.0,0.0,1.0,2003,0.000010,True,REGULAR,USD
1,SPY260724C00505000,2026-07-13 16:56:30+00:00,505.0,245.53,231.20,234.29,0.0,0.0,NaN,1,3.661134,True,REGULAR,USD
2,SPY260724C00510000,2026-07-13 16:56:45+00:00,510.0,240.41,225.90,229.29,0.0,0.0,NaN,1,3.578126,True,REGULAR,USD
3,SPY260724C00515000,2026-07-23 19:44:12+00:00,515.0,221.74,221.21,224.30,0.0,0.0,1.0,1,3.500978,True,REGULAR,USD
4,SPY260724C00520000,2026-07-23 19:45:39+00:00,520.0,216.68,216.20,219.30,0.0,0.0,2.0,2,3.419923,True,REGULAR,USD

In [10]:
filtered_calls = calls[
    (calls["openInterest"] >= 100) &
    (calls["volume"] >= 10)
].copy()

In [11]:
filtered_calls[
    [
        "strike",
        "lastPrice",
        "impliedVolatility",
        "volume",
        "openInterest"
    ]
].head(10)

     strike  lastPrice  impliedVolatility  volume  openInterest
73    700.0      38.75           0.716800    39.0           379
96    723.0      16.20           0.310554    87.0           327
98    725.0      12.94           0.000010    32.0           616
99    726.0      11.60           0.000010    10.0           284
100   727.0      11.00           0.152352   264.0           896
101   728.0      10.00           0.140634    28.0           498
102   729.0       9.15           0.000010   141.0           535
103   730.0       7.75           0.000010   304.0           808
104   731.0       7.12           0.000010   294.0           418
105   732.0       5.80           0.000010   376.0          1311

In [12]:
filtered_calls["IV %"] = filtered_calls["impliedVolatility"] * 100

filtered_calls[
    [
        "strike",
        "IV %"
    ]
].head(10)

     strike       IV %
73    700.0  71.679971
96    723.0  31.055377
98    725.0   0.001000
99    726.0   0.001000
100   727.0  15.235223
101   728.0  14.063359
102   729.0   0.001000
103   730.0   0.001000
104   731.0   0.001000
105   732.0   0.001000

In [13]:
print(
    "Average IV:",
    filtered_calls["IV %"].mean()
)

Average IV: 33.1695709085836

In [14]:
filtered_calls.nlargest(
    5,
    "impliedVolatility"
)[
    [
        "strike",
        "IV %"
    ]
]

     strike        IV %
192   895.0  109.375453
191   890.0  106.250469
190   885.0  103.125484
188   875.0   96.875031
187   870.0   93.750062

In [15]:
filtered_calls.nsmallest(
    5,
    "impliedVolatility"
)[
    [
        "strike",
        "IV %"
    ]
]

     strike   IV %
98    725.0  0.001
99    726.0  0.001
102   729.0  0.001
103   730.0  0.001
104   731.0  0.001